apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 920372986500.dkr.ecr.us-east-1.amazonaws.com/nagecr:14959702464-16
          imagePullPolicy: Always
          ports:
            - containerPort: 8080